"""
Basic program that generates bottom N order prices of the specified items
"""

import asyncio
import json
import logging
import logging.config

from wfmarkettool import WFMarketTool

config = {}
with open("cfg/logger.json") as cfg:
    config = json.load(cfg)
    config["handlers"]["file"]["filename"] = f"{__name__}.log"

logging.config.dictConfig(config)
logger = logging.getLogger(__name__)


async def main() -> None:
    items = {
        # "overextended",
        # "narrow_minded",
        # "catalyzing_shields",
        # "blind_rage",
        # "galvanized_chamber",
        # "galvanized_aptitude",
        # "galvanized_chamber",
        # "galvanized_aptitude",
        # "galvanized_scope",
        # "galvanized_hell",
        # "galvanized_savvy",
        # "galvanized_acceleration",
        # "galvanized_diffusion",
        # "galvanized_shot",
        # "galvanized_crosshairs",
        # 'kaszas_handle',
        # 'velocitus_receiver',
        # 'corvas_stock',
        # 'agkuza_guard',
        # 'fluctus_stock',
        # 'scattered_justice',
        # 'justice_blades',
        # 'neutralizing_justice',
        # 'shattering_justice',
        # 'path_of_statues',
        # 'tectonic_fracture',
        # 'ore_gaze',
        # 'titanic_rumbler',
        # 'rubble_heap',
        # 'recrystalize',
        # 'fireball_frenzy',
        # 'immolated_radiance',
        # 'healing_flame',
        # 'exothermic',
        # 'surging_dash',
        # 'radiant_finish',
        # 'furious_javelin',
        # 'chromatic_blade',
        # 'freeze_force',
        # 'ice_wave_impedance',
        # 'chilling_globe',
        # 'icy_avalanche',
        # 'biting_frost',
        # 'dread_ward',
        # 'blood_forge',
        # 'blending_talons',
        # 'gourmand',
        # 'hearty_nourishment',
        # 'catapult',
        # 'accumulating_whipclaw',
        # 'venari_bodyguard',
        # 'pilfering_strangledome',
        # 'wrath_of_ukko',
        # 'ballistic_bullseye',
        # 'staggering_shield',
        # 'muzzle_flash',
        # "mesas_waltz",
        # 'pyroclastic_flow',
        # 'reaping_chakram',
        # 'safeguard',
        # 'divine_retribution',
        # 'controlled_slide',
        # 'teeming_virulence',
        # 'larva_burst',
        # 'parasitic_vitality',
        # 'insatiable',
        # 'abundant_mutation',
        # 'neutron_star',
        # 'antimatter_absorb',
        # 'escape_velocity',
        # 'molecular_fission',
        # 'smite_infusion',
        # 'hallowed_eruption',
        # 'phoenix_renewal',
        # 'hallowed_reckoning',
        # 'ironclad_charge',
        # 'iron_shrapnel',
        # 'piercing_roar',
        # 'reinforcing_stomp',
        # 'venom_dose',
        # 'revealing_spores',
        # 'regenerative_molt',
        # 'contagion_cloud',
        # "ulfruns_endurance",
        # 'vampiric_grasp',
        # 'the_relentless_lost',
        # 'vaykor_marelok',
        # 'vaykor_hek',
        # 'vaykor_sydon',
        # 'kaszas_blade',
        # 'velocitus_stock',
        # 'rathbone_handle',
        # 'agkuza_handle',
        # 'fluctus_limbs',
        # 'gleaming_blight',
        # 'eroding_blight',
        # 'stockpiled_blight',
        # 'toxic_blight',
        # 'seeking_shuriken',
        # 'smoke_shadow',
        # 'fatal_teleport',
        # 'rising_storm',
        # 'path_of_statues',
        # 'tectonic_fracture',
        # 'ore_gaze',
        # 'titanic_rumbler',
        # 'rubble_heap',
        # 'recrystalize',
        # 'fireball_frenzy',
        # 'immolated_radiance',
        # 'healing_flame',
        # 'exothermic',
        # 'warriors_rest',
        # 'dread_ward',
        # 'blood_forge',
        # 'blending_talons',
        # 'gourmand',
        # 'hearty_nourishment',
        # 'catapult',
        # 'tribunal',
        # 'warding_thurible',
        # 'lasting_covenant',
        # 'accumulating_whipclaw',
        # 'venari_bodyguard',
        # 'pilfering_strangledome',
        # 'swift_bite',
        # 'valence_formation',
        # 'savior_decoy',
        # 'damage_decoy',
        # 'hushed_invisibility',
        # 'safeguard_switch',
        # 'irradiating_disarm',
        # 'ballistic_bullseye',
        # 'staggering_shield',
        # 'muzzle_flash',
        # 'mesas_waltz',
        # 'soul_survivor',
        # 'creeping_terrify',
        # 'despoil',
        # 'shield_of_shadows',
        # 'venom_dose',
        # 'revealing_spores',
        # 'regenerative_molt',
        # 'contagion_cloud',
        # 'spellbound_harvest',
        # 'beguiling_lantern',
        # 'razorwing_blitz',
        # 'ironclad_flight',
        # 'shock_trooper',
        # 'shocking_speed',
        # 'transistor_shield',
        # 'capacitance',
        # 'ulfruns_endurance',
        # 'target_fixation',
        # 'airburst_rounds',
        # 'jet_stream',
        # 'funnel_clouds',
        # 'anchored_glide',
        # 'rakta_ballistica',
        # 'rakta_cernos',
        # 'rakta_dark_dagger'
        "critical_surge",
        "mind_freak",
        "pacifying_bolts",
        "assimilate",
    }
    tool = WFMarketTool(logger)
    await tool.initialize()

    await tool.print_multiple_floor_prices(list(items))

    await tool.close()


if __name__ == "__main__":
    main_task = asyncio.run(main())
